sabbath:
  name: Developer

spring:
  jackson:
    time-zone: Europe/Moscow
  datasource:
    username: sabbath
    password: sabbath
    url: jdbc:postgresql://postgres:5432/market
    hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        enable_lazy_load_no_trans: true
        current_session_context_class: thread
        generate_statistics: true
    hibernate:
      ddl-auto: create-drop