server:
  port: 8881

spring:
  datasource:
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
    url: 'jdbc:postgresql://postgres:5432/postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        enable_lazy_load_no_trans: true
        current_session_context_class: thread
        generate_statistics: true
    hibernate:
      ddl-auto: create-drop

gateway:
  uri: http://gateway:8888/api/v1

management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

  endpoints:
    web:
      exposure:
        include: '*'

  metrics:
    web:
      server:
        auto-time-requests: true
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  config: 'classpath:log4j2.yml'

my:
  property: 'aaaaaaaaaaaaaaaaa'