server:
  port: 0

spring:
  datasource:
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
    url: 'jdbc:postgresql://postgres:5432/postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        enable_lazy_load_no_trans: true
        current_session_context_class: thread
    hibernate:
      ddl-auto: create-drop

logging:
  config: 'classpath:log4j2.yml'