version: '3'

services:

  consul:
    image: sabbath666/consul-server
    container_name: consul
    volumes:
      - ./consul/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8500:8500"
    restart: always

  gateway:
    image: sabbath666/gateway-service
    container_name: gateway-service
    ports:
      - 8888:8888
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  ui-service:
    image: sabbath666/ui-service
    container_name: ui-service
    environment:
      SERVER_PORT: 9999
      SPRING_CLOUD_CONSUL_HOST: consul
      GATEWAY_URI: http://gateway-service:8888/api/v1
    ports:
      - 9999:9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  client-service:
    image: sabbath666/client-service
    container_name: client-service
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_PROFILES_ACTIVE: test
      GATEWAY_URI: http://gateway:8888/api/v1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  bank-service:
    image: sabbath666/bank-service
    container_name: bank-service
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_PROFILES_ACTIVE: test
      GATEWAY_URI: http://gateway:8888/api/v1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  credit-service:
    image: sabbath666/credit-service
    container_name: credit-service
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_PROFILES_ACTIVE: test
      GATEWAY_URI: http://gateway:8888/api/v1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  check-service:
    image: sabbath666/check-service
    container_name: check-service
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_PROFILES_ACTIVE: test
      GATEWAY_URI: http://gateway:8888/api/v1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  postgres:
    image: postgres:11
    container_name: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always


