version: '3'

services:

  graylog:
#    network_mode: host
    image: graylog/graylog:2.5.1-3
    container_name: graylog
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      GRAYLOG_WEB_ENDPOINT_URI: "http://127.0.0.1:9000/api"
    ports:
      - "9000:9000"
      - "12201:12201/tcp"
      - "514:514/udp"
      - "5555:5555"

  mongo:
#    network_mode: host
    image: mongo:3
    container_name: mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro

  elasticsearch:
#    network_mode: host
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: elasticsearch
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx4g"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      http.host: "0.0.0.0"
      bootstrap.memory_lock: "true"
      ulimit memlock: "-1:-1 "




