version: '3'

services:

  emulator-service:
    image: sabbath666/emulator-service
    container_name: emulator-service
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_PROFILES_ACTIVE: test
      GATEWAY_URI: http://gateway:8888/api/v1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

