version: '3'

services:

  consul:
    image: consul:1.4.2
    container_name: consul
    volumes:
      - ./consul/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8500:8500/tcp"
    command:
      'agent -server -bootstrap-expect=1 -ui -data-dir=/data -client=0.0.0.0 -bind=0.0.0.0'
    restart: always

  gateway:
    image: sabbath666/gateway-service
    container_name: gateway-service
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  ui-service:
    image: sabbath666/ui-service
    container_name: ui-service
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  client-service:
    image: sabbath666/client-service
    container_name: client-service
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  bank-service:
    image: sabbath666/bank-service
    container_name: bank-service
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  credit-service:
    image: sabbath666/credit-service
    container_name: credit-service
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  check-service:
    image: sabbath666/check-service
    container_name: check-service
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always


  postgres:
    image: postgres:11
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always


