version: '3'

services:

  ui-service:
    image: sabbath666/ui-service
    container_name: ui-service
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      GATEWAY_URI: http://gateway:8888/api/v1
    ports:
      - 9999:9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always



