version: '3'

#volumes:
#  pgdb:

services:
  redis:
    image: redis

  postgres:
    container_name: pg_sentry
    image: postgres
    ports:
      - "5454:5454"
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
#    volumes:
#      - pgdb:/var/lib/postgresql/data

  sentry:
    image: sentry
    container_name: sentry
    ports:
      - 9009:9009
    environment:
      SENTRY_SECRET_KEY: '!!!SECRET!!!'
      SENTRY_POSTGRES_HOST: pg_postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis

  cron:
    image: sentry
    links:
      - redis
      - postgres
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: '!!!SECRET!!!'
      SENTRY_POSTGRES_HOST: pg_postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis

  worker:
    image: sentry
    links:
      - redis
      - postgres
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: '1485f9cf--478d-ab69-9b73c3eadb18'
      SENTRY_POSTGRES_HOST: pg_sentry
      SENTRY_POSTGRES_PORT: 5454
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis