version: '3'

services:

  consul:
    network_mode: host
    image: consul:1.4.2
    container_name: consul
    volumes:
      - ./consul/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1-65535:1-65535"
    command:
      'agent -server -bootstrap-expect=1 -ui -data-dir=/data -bind=127.0.0.1'
    restart: always

  postgres:
    image: postgres:11
    container_name: postgres
    network_mode: host
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

