version: '3'

services:

  consul:
    image: consul:1.4.2
    container_name: consul
    volumes:
      - ./consul/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8500:8500/tcp"
    command:
      'agent -server -bootstrap-expect=1 -ui -data-dir=/data -client=0.0.0.0 -bind=0.0.0.0'
    restart: always

  postgres:
    image: postgres:11
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
