server:
  port: 0

jsf:
  adminfaces:
    skin: skin-blue
  primefaces:
    theme: admin
    font-awesome: true
  datetimeconverter-default-timezone-is-system-timezone: true

spring:
  profiles:
    active: dev

gateway:
  uri: http://localhost:8888/api/v1

logging:
  config: classpath:log4j2.yml
