server:
  port: 9999

jsf:
  adminfaces:
    skin: skin-blue
  primefaces:
    theme: admin
    font-awesome: true
  datetimeconverter-default-timezone-is-system-timezone: true

gateway:
  uri: http://gateway:8888/api/v1

logging:
  config: classpath:log4j2.yml
