server:
  port: 0

gateway:
  uri: http://localhost:8888/api/v1

logging:
  config: 'classpath:log4j2.yml'

spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

#sentry:
#  sample:
#    rate: 1
#  dsn: "http://4aab3cb2ac70479ba33eeb4f4fdba1b8@localhost:9010/2"