global:
  scrape_interval: 5s
  evaluation_interval: 5s

  external_labels:
    monitor: 'prometheus-grafana-exporter'


rule_files:
  - rules.yml


alerting:
  alertmanagers:
    - static_configs:
        - targets: [alertmanager:9093]


scrape_configs:
  - job_name: consul
    consul_sd_configs:
      - server: 'consul:8500'
        services: []
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job

  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  - job_name: node
    static_configs:
      - targets: [nodeexporter:9100]

remote_write:
  - url: "http://prometheus_db_adapter:9201/write"

remote_read:
  - url: "http://prometheus_db_adapter:9201/read"

